version: '3.8'
services:
  node:
    restart: always
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./:/code
  
  client:
    build: ../Tasks-UI/client/app
    ports:
      - 8080:8080
    volumes:
      - ../Tasks-UI/client/app:/app2
      - /app2/node_modules

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db

volumes:
  mongodb: